### ISSUE TITLE
[React] Duplicate styles in react bundle

### ISSUE THREAD

**Issue by niwsa** [boxyhq/ui#419]
## Problem
The vite build setup for react uses [vite-plugin-css-injected-by-js](https://www.npmjs.com/package/vite-plugin-css-injected-by-js) plugin to inject the CSS styles using javascript. Some stylesheets like [common.module.css](https://github.com/boxyhq/ui/blob/main/src/shared/common.module.css) are sourced in multiple [other](https://github.com/boxyhq/ui/blob/eb004219b582cdcb24d3aa7103c16baaab30c330/src/shared/Well/index.module.css#L1) stylesheets. The styles coming from `common.module.css` get injected multiple times in the final bundle (`react/dist/shared.js`). Find a way to get rid of the repeated styles in the bundle.

## Solution
Source `common.module.css` inside `sso/index.ts` and remove CSS imports `@import` inside *.module.css. 
**NOTE**: Any better alternatives are also welcome.

## Testing
Make changes under `src/shared` folder. Run `npm run build` from root folder followed by `npm run build-lib` under `react` folder. Verify that the classnames are not repeated inside `react/dist/shared.js`

**Comment by jatinmark** [comment]
I want to work on this issue can you assign it to me .

**Comment by niwsa** [comment]
Thank you :) @jatinmark. I am assigning it to you. Feel free to let me know if you have any questions.

**Comment by asi309** [comment]
Is this open? I would like to work on this

**Comment by niwsa** [comment]
@jatinmark Are you working on this issue?

**Comment by jatinmark** [comment]
yes i am working on it .

**Comment by niwsa** [comment]
@jatinmark @asi309 I will have to close this one as we are in the process of [making](https://github.com/boxyhq/ui/pull/433) some changes to the manner in which the styles have to be loaded for the UI components. We must forego the CSS injection plugin since its default behavior is auto-injecting CSS styles into the `<head>` tag which might make it load after the app styles. This might make it difficult for library users to set custom theming/styles.

**Comment by jatinmark** [comment]
ok .
