### ISSUE TITLE
Loading state for save/update buttons

### ISSUE THREAD

**Issue by niwsa** [boxyhq/ui#430]
## Issue
The [`Button`](https://github.com/boxyhq/ui/blob/main/src/shared/Button/index.lite.tsx) component currently lacks a loading indicator that provides visual feedback for an ongoing operation.

## Solution
Support an `isLoading` prop and display a spinner if it's true. For reference see: https://react.daisyui.com/?path=/story/actions-button--loading-spinner-and-text

## Before you begin
Kindly go through the [guidelines](https://github.com/boxyhq/hacktoberfest-23#-contributing-to-boxyhq) before making your contribution. Happy hacking !! 😃

**Comment by asi309** [comment]
Can you provide a description of this issue. I would like to work on this
